### ISSUE TITLE
Clarify resource type in search list

### ISSUE THREAD

**Issue by hminsky2002** [OpenTechStrategies/arches-app-exp#73]
Issue as described by @kfogel 
> In the list of results that shows up below the search box, move the type indicator ("Structure", "Artwork", "Artist", etc) from above the actual result to below it, and make the font italicized, and make it even smaller relative to the result text, so that it's super-easy to distinguish it from the substantive part of the result.

**Comment by reefdog** [comment]
Gosh, there are a lot of related requests, lol. I think my idea posted in #84 probably actually belongs _here_, but they're probably all related. In any case, a suggested way of calling attention to type in search results:

<img width="598" alt="Search results" src="https://github.com/user-attachments/assets/59f76e87-5e9a-46d0-9123-be971500a356">

**Comment by reefdog** [comment]
Wait, now that we don't have an "Everything" view that mixes types together… do we even need this?

**Comment by kfogel** [comment]
I think you're right, @reefdog -- we don't need it now (though it was a neat idea!).

**Comment by reefdog** [comment]
@kfogel Great, I'll close this as a wontfix for now.
