### ISSUE TITLE
Feedback on UI as of 856575e20c1f929c65118f766eed3cf591381a31

### ISSUE THREAD

**Issue by hminsky2002** [OpenTechStrategies/arches-app-exp#82]
This issue contains UI feedback from @kfogel as of our meeting this afternoon:

- [x] Remove the feature on search-items where the underline dissapears on mouse hover
- [x] Add colons to photographer and arches metadata
- [x] Don’t show additional artworks unless there are more than one for a given artwork page
- [x] We should link to the arches resource ui from the metadata links
- [x] We need to distinguish search bar default text based on the resource type being filtered

**Comment by reefdog** [comment]
> Remove the feature on search-items where the underline dissapears on mouse hover

Whoops! I didn't realize this was a specific desire. I just reverted this change accidentally, not realizing it had been removed, in my #90. Will re-revert.

**Comment by reefdog** [comment]
> Don’t show additional artworks unless there are more than one for a given artwork page

I see this as checked but I'm not seeing this behavior locally, thus opening #89. Is it… supposed to be working?
