### ISSUE TITLE
Refactor the Artwork search-items to have their artist information instead of resource type, located under title

### ISSUE THREAD

**Issue by hminsky2002** [OpenTechStrategies/arches-app-exp#83]
Beyond those issues listed in #82, this requires a refactor of the search item component to have access to a related artist for an artwork. This will thus take a few more lines of logic and has been extracted into a separate issue

**Comment by reefdog** [comment]
Related comment: https://github.com/OpenTechStrategies/arches-app-exp/issues/84#issuecomment-2356415649
