### ISSUE TITLE
Refactor Artist search-items to have 'artist:' appended in front of the artist name, instead of above it

### ISSUE THREAD

**Issue by hminsky2002** [OpenTechStrategies/arches-app-exp#84]

**Comment by reefdog** [comment]
I don't _love_ the idea of interleaving metadata into data, particularly for the most prominent/title element.

Can someone describe the need/desire here, and I can explore some alternative display options?

**Comment by reefdog** [comment]
For instance, we could move the type to a vertical tag along the side of the image:

<img width="653" alt="Artwork tag" src="https://github.com/user-attachments/assets/ef306f0b-83dd-41fd-94fa-aa406b200195">

Perhaps with color-coding based on type, and perhaps with a little more artistic display:

<img width="605" alt="Artwork/Artist tags" src="https://github.com/user-attachments/assets/8d4af5c0-8d60-4884-bbb7-fd6b7050246f">

**Comment by hminsky2002** [comment]
After discussion with @kfogel we've decided that the simplest way to clarify things for the time being is simply to remove the artwork tag from artworks, and leave artists as is. In the case that we reintroduce more resource models, @reefdog I am a huge fan of this design!
