### ISSUE TITLE
Update About/Credit text in footer

### ISSUE THREAD

**Issue by reefdog** [OpenTechStrategies/arches-app-exp#95]
From @kfogel in #33:

> * For the "About / Credit" text at the bottom (I haven't tested this HTML, so please fix as needed):
>       
>         <p>This site is a project of <a
>         href="https://opentechstrategies.com/" >Open Tech Strategies,
>         LLC</a>.  Our thanks to the artists and curators who created and
>         continue to build the <a
>         href="https://students.colum.edu/deps/wabash-arts-corridor"
>         >Wabash Arts Corridor</a> in Chicago.  Please write us at
>         info@opentechstrategies.com to suggest changes or improvements
>         to this site.</p>
> 
>         <p>This site is <a href="SEE_BELOW" >free &amp; open source
>         software</a>, based on the <a href="https://www.archesproject.org/"
>         >Arches</a> heritage data management platform.</p>
>       
>   That "SEE_BELOW" link should link to a "/technical-info" page that has the following content:
>       
>         <p>This site is free &amp; open source software.  See the <a 
>         href="https://github.com/OpenTechStrategies/arches-app-exp"
>         >application code</a>, the <a
>         href="https://code.librehq.com/ots/arches/arches-demo-data/-/tree/main/wac"
>         >data</a>, and our <a
>         href="https://code.librehq.com/ots/arches/arches-sites/-/tree/main/ots/wac"
>         >data import scripts</a>.  Contributions welcome.</p>
>       
>   Did I get all the above URLs right?  Please correct if any are wrong, and let me know of course.

**Comment by reefdog** [comment]
@kfogel Are you wedded to a `/technical-info` page? It's trivial (and IMO preferable from a user perspective) to include all that info right there in the footer rather than making folks click through.

So I would suggest the following footer:

> This site is a project of [Open Tech Strategies, LLC](https://opentechstrategies.com/). Our thanks to the artists and curators who created and continue to build the [Wabash Arts Corridor](https://students.colum.edu/deps/wabash-arts-corridor) in Chicago. Please write us at [info@opentechstrategies.com](mailto:info@opentechstrategies.com?subject=Explore%20Wabash%20Arts%20Corridor%20site) to suggest changes or improvements to this site.
>
> This site is free & open source software, based on the [Arches](https://www.archesproject.org/) heritage data management platform. See the [application code](https://github.com/OpenTechStrategies/arches-app-exp), the [data](https://code.librehq.com/ots/arches/arches-demo-data/-/tree/main/wac), and our [data import scripts](https://code.librehq.com/ots/arches/arches-sites/-/tree/main/ots/wac). Contributions welcome.

**Comment by kfogel** [comment]
@reefdog I'm fine with that, sure.  Thanks!
