### ISSUE TITLE
Zoom to and highlight active item on map

### ISSUE THREAD

**Issue by reefdog** [OpenTechStrategies/arches-app-exp#96]
When you've navigated to the resource detail page for a piece of artwork, we should zoom the map to that pin (we'll probably want to fine-tune the zoom level during development), and custom-format the pin (larger + `#ffe16a`?).

**Comment by hminsky2002** [comment]
@reefdog something I was wondering actually was did you have any thoughts on the map icons themselves? we theoretically could use any image we want, these are just the ones provided by leaflet. Conversely, they are perfectly serviceable. Just wanted to bring it up!

**Comment by reefdog** [comment]
Oh yeah, I'd love to do a design pass on the map itself. For now if we can at least add the zoom and highlight functionality more can wait — but I'll open a task!

**Comment by reefdog** [comment]
Delivered by #99 and #102.
